### ISSUE TITLE
account history improvements/bugs

### ISSUE THREAD

**Issue by robby-d** [CounterpartyXCP/counterwallet#308]
- **track BTC payments**: right now BTC transactions are not tracked in account history. let's enhance the history screen to track this
- **not all transactions listed**: sometimes, maybe not all transactions are properly listed, e.g.: "The history output on counterwallet.co is woefully incomplete. None
  of the BTC coming in and going out are shown, and only half of the
  transactions of SWARMPRE I received are showing."

**Comment by rippler** [comment]
We still get reports that even Counterparty (i.e. sends of Counterparty assets) don't appear in History. This is in addition to other Counterparty-based transactions that don't appear in History.
