### ISSUE TITLE
Signed messages don't verify in bitcoind

### ISSUE THREAD

**Issue by robby-dermody** [CounterpartyXCP/counterwallet#309]
"tried verifying a signed message from it in bitcoin-qt and just returns false"
"but works from electrum for e.g"

**Comment by romerun** [comment]
is there an update on this ?

and in the meantime, is there a way to verify the messages signed by counterwallet programmatically ?

**Comment by andreasanastas** [comment]
> is there an update on this ?
> 
> and in the meantime, is there a way to verify the messages signed by counterwallet programmatically ?

This

**Comment by mtbitcoin** [comment]
I would assume you can verify signed messages via the bitcore.io lib because that is what counterwallet is using

**Comment by ouziel-slama** [comment]
@romerun: you can try something like this with Bitcore 1.0:

````
    var bitcore = require('bitcore');
    var message = "test";
    var privkey = "cRBmDXWNDs7UbGbhe4tBSqvM3FxaUDbq2Jy3xwam1vBvvgjCqwBp";
    var walletKey = new bitcore.WalletKey({network: bitcore.networks.testnet});

    walletKey.fromObj({priv:privkey});

    var address = this.walletKey.storeObj().addr;
    console.log(address);

    var signature = bitcore.Message.signMessage(message, walletKey.privKey).toString('base64');
    console.log(signature);

    var result = bitcore.Message.verifyMessage(address, message, signature);
    console.log(result);
````

**Comment by romerun** [comment]
thank you @ouziel-slama, but the code no longer work with recent versions of bitcore. It looks like bitcore.Message has been moved to somewhere since v0.8 .

**Comment by ouziel-slama** [comment]
@romerun, yep. In CW we are using the version 0.1: https://github.com/bitpay/bitcore/tree/v0.1
(I fixed my previous message)

**Comment by romerun** [comment]
the code did not work for me. The end result is false. So I went to ask on bitcore github, they say it's a known issue.

https://github.com/bitpay/bitcore/issues/1002

which could means not only does counterwallet signed message not work with the official client, it also cannot be verified by the library signing it.

**Comment by robby-dermody** [comment]
fixed with the bitcore update earlier this year, and the wallet now produces base64.
