### ISSUE TITLE
[enh] Ability to pass asset name in URL to open its page on DEx

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterwallet#403]
Basically it'd be like https://counterwallet.co/asset=<SYMBOL>.

If this can be done, it may be interesting to consider other things (e.g. feed address).

Good:
1. Symbol names would become less relevant
2. Significantly lower possibility of typos/mistakes
3. Easier/faster navigation to buy/sell assets

**Comment by robby-dermody** [comment]
closing in favor of #111
