### ISSUE TITLE
Rounding issues

### ISSUE THREAD

**Issue by btcdrak** [CounterpartyXCP/counterwallet#417]
Latest master of counterwallet and counterblockd renders the following discrepancy. The price is rendered differently in the open orders section to the order book.. Below is an order where the price is `1`, but rendered as `0.99999999` on the orderbook.

![https testnet clearwallet co pages exchange html](https://cloud.githubusercontent.com/assets/7275704/4163643/cb8931e8-34e9-11e4-841d-48bf31eec49e.png)

**Comment by robby-dermody** [comment]
closing. please reopen if this can be reproduced
