### ISSUE TITLE
Signing of raw transactions doesn't work

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterwallet#436]
How to reproduce:
1. Create raw tx at betxcp.com ("bet code")
2a. In CW paste it into Betting > Make a Bet. Result: "We can't find a feed at this address"
Also copying feed address doesn't work, so maybe there's something wrong with the extended feed info, but there's another way.
2b. Copy raw tx and from the CW XCP address used to create the raw tx try to sign and broadcast -> Result "Invalid hex string"

One workaround: use http://redeem.bitwatch.co/
Support: 246

**Comment by ouziel-slama** [comment]
see https://github.com/CounterpartyXCP/counterwallet/issues/670
