### ISSUE TITLE
CW address BTC balance inconsistent with the outside world

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterwallet#458]
![balance_inconsistent](https://cloud.githubusercontent.com/assets/4045519/4348956/09c6ea66-41a3-11e4-88e1-7b2e34a731fa.png)

Maybe I'm missing something but there doesn't seem to be recent BTC-related transactions that could explain the difference between the real (close to 0) and displayed (close to 0.48):
https://blockchain.info/address/1HiBGx4e6VCA1K4cxNQctUuZJDt4f2unyQ

**Comment by ouziel-slama** [comment]
resolved with jmcorgan
