### ISSUE TITLE
Reword manual pay message

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterwallet#535]
>"btcpay_required": "A payment on a matched order for <b class='notoQuantityColor'>%s</b> <b class='notoAssetColor'>BTC</b> is required, however, the address that made the order (<b class='notoAddrColor'>%s</b>) lacks the balance necessary to do this automatically. This order has been placed in a pending state.<br/><br/>Please deposit the necessary <b class='notoAssetColor'>BTC</b> into this address and manually make the payment from the Bitcoin icon in the top bar of the site.",

It doesn't say within what period of time, which I find slightly concerning. 
Could we add "within 19 blocks from the block during which you received this message" or something like that?

**Comment by robby-dermody** [comment]
closing as BTCpay functionality removed from CW
