### ISSUE TITLE
Disclaimer against scams banner on 'Buy/Sell' Page

### ISSUE THREAD

**Issue by evanwagner1** [CounterpartyXCP/counterwallet#543]
"Warning and Disclaimer: the hosts of Counterwallet.io and Counterwallet.co _do not_ filter very likely scam or fraudulent assets, and explicitly disclaim any responsibility therefor. Caveat emptor: do your own diligence, and do not invest more than you can afford to lose."

**Comment by junseth** [comment]
"Warning and Disclaimer: the hosts of Counterwallet.io and Counterwallet.co do not filter very likely scam or fraudulent assets, and explicitly disclaim any responsibility therefor. Caveat emptor: do your own diligence, and do not invest more than you can afford to lose." has a misspelling. It should be written:

"Warning and Disclaimer: the hosts of Counterwallet.io and Counterwallet.co do not filter very likely scams or fraudulent assets, and explicitly disclaim any responsibility therefore. Caveat emptor: do your own diligence, and do not invest more than you can afford to lose."
