### ISSUE TITLE
Move errors from pop-ups/alerts to an appended log

### ISSUE THREAD

**Issue by hizzvizz** [CounterpartyXCP/counterwallet#562]
problem:

When I leave the counterwallet open for several hours, I always see this error "Got an error when trying to sync BTC balances: timeout". This is being displayed as a pop-up and there are hundreds of these errors. restarting the browser doesn't get around that if this app is open for several hours, these errors pop up.

solution:

Can you move any errors to a separate page with an appended log? This way the errors aren't lost, and the pop-ups don't bog down the user experience.

**Comment by robby-dermody** [comment]
fixed in https://github.com/CounterpartyXCP/counterwallet/commit/fed6bfdb1ea2d5c6240cae94e8105b3b3d78a751
