### ISSUE TITLE
Force users to accept terms and conditions on Quick Buy page

### ISSUE THREAD

**Issue by vennd** [CounterpartyXCP/counterwallet#575]
As an interim measure, we would request to force the user to accept a terms and conditions page upon going into the Quick Buy page. This is only necessary to be accepted once.

We will provide the text that needs to go into the terms and conditions.

Upon accepting the terms, the user can click 'I accept' or 'I do not accept'. If the user accepts, they may use the Quick Buy page. If the user does not accept, they are returned to the screen they previously came from.

**Comment by vennd** [comment]
@ouziel-slama, yep - we'll be asking a contractor to implement this though. I'll see if we can assign it to him.

**Comment by robby-dermody** [comment]
closing due to lack of vend support in cw, please reopen if this is still something that needs to be done
