### ISSUE TITLE
Can autoBTCEscrowServer still be used?

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterwallet#628]
```
"autoBTCEscrowServer": "btcescrow.counterwallet.co"
```
Source: http://counterparty.io/docs/build-system/federated-node/

Since BTCPay is disabled, this could be removed, right?

**Comment by ouziel-slama** [comment]
right!

**Comment by rippler** [comment]
Done (https://github.com/CounterpartyXCP/counterpartyd_build/pull/174)
