### ISSUE TITLE
Display full multi-sig address

### ISSUE THREAD

**Issue by goodtaster** [CounterpartyXCP/counterwallet#637]
Shows up as "1NThD...X9tXK, 1PdFM...apVJJ"

Is there anything I'm missing? It's not clickable as far as I can tell.

**Comment by rippler** [comment]
It should probably be displayed in rows.
A "copy to clipboard" action on addresses would be useful (not just here but also here too) because on mobile devices it's a nightmare to select and copy that stuff.

**Comment by SouKw** [comment]
Counterwallet does not display the QR code for the multisig address. Also, the user has no way to copy the multisig address by hand because there it is not show, just "1NThD...X9tXK, 1PdFM...apVJJ". How to send to the multisig address if does not copy or QR?

**Comment by ninjaboon** [comment]
I have the same error. Hope they can resolve this soon. Is there a way to manually to generate /copy the full multi-sig address?

**Comment by cryptonaut420** [comment]
I've been confused by this as well.. as far as I can tell its completely unusable.

Don't multisig addresses look like this: 3EffXJKyYB9zWh2dhx2hcccqBK8DGC7x2x

and not 1NThD...X9tXK, 1PdFM...apVJJ ?

I get that it should show each address which is required to sign, but there doesnt seem to be a way to get the actual usable multisig address

**Comment by ninjaboon** [comment]
If you go to the history section on Counterwallet, you will see the full add for the multisig add.

**Comment by ouziel-slama** [comment]
The address is now clickable and open the change label dialog.
The change label dialog shows the full multisig address with the format n_addr1_addr2_m.
