### ISSUE TITLE
get_normalized_balance error for specific address

### ISSUE THREAD

**Issue by mstg** [CounterpartyXCP/counterwallet#663]
Hello!
My address: 16mdGJsnCJT3nmGmqyiMi3U4Nry67HdzcL
Counterwallet gives an get_normalized_balance error when trying to login to wallet with that address or adding it as a watch only/armory offline wallet.

**Comment by ouziel-slama** [comment]
@mstg : Just add this address as a watch only address and works well. Maybe was a temporary server problem. Feel free to re-open is not resolved.
