### ISSUE TITLE
[Graphics] Exchange -> Select Another Pair

### ISSUE THREAD

**Issue by goodtaster** [CounterpartyXCP/counterwallet#667]
![graphics](https://cloud.githubusercontent.com/assets/6738500/5837029/5df606e8-a130-11e4-9f34-64876dc71ec8.png)

(both Chrome & Firefox, latest)

**Comment by ouziel-slama** [comment]
fixed

**Comment by goodtaster** [comment]
It's fine in Firefox now, but in Chrome it does this.

![pairglitch](https://cloud.githubusercontent.com/assets/6738500/6059628/3cac1a6c-ad34-11e4-8aec-d568eb934710.png)
