### ISSUE TITLE
Regenerate counterwallet xpriv key using bitcore

### ISSUE THREAD

**Issue by mtbitcoin** [CounterpartyXCP/counterwallet#676]
I am trying to regenerate the xpriv key using the standalone client side bitcore library by using the same mnemonic phrase used in counterwallet. Is this possible ? 

It looks like the mnemonic phrases generated by standalone bitcore is not compatible with counterwallet and vice versa.  

For the bitcore side of things I am using the following sample at http://bitcore.io/guide/hierarchical.html

**Comment by rippler** [comment]
This isn't a direct answer, but maybe it helps:
http://support.counterparty.io/support/articles/5000012278-is-it-possible-to-create-the-list-of-addresses-from-counterwallet-pass-phrase-

**Comment by mtbitcoin** [comment]
@rippler Thanks! That helped a lot

**Comment by mtbitcoin** [comment]
@rippler  I've built a standalone online key/address generator that uses the 12 word counterwallet mnemonic passphrase with the help of your link. This should hopefully assists in alleviating concerns regarding access issues in retrieving keys if counterwallet is down or just as a quick tool to generate the list of available deterministic addresses associated with the 12 words passphrase

**Comment by rippler** [comment]
@mtbitcoin excellent! 
"I've always wondered but never dared to ask" (or tried to check) if CW and the utility generate addresses in exactly the same order, hopefully that's the case

**Comment by mtbitcoin** [comment]
Yea. Same here. Also, the process was somewhat more involved with the python script..

I was looking for something more simple, just point and click but did not find one. This saves a lot of time as I do not have to back up my private keys manually (for peace of mind "just in case" they could not be retrieved)

The entire script is in html, javascript + css so the source is indirectly viewable online. Any audits and feedback is welcomed.
