### ISSUE TITLE
Creating MultiSig wallet

### ISSUE THREAD

**Issue by julian-smith-code** [CounterpartyXCP/counterwallet#686]
When I attempt to create a multisig wallet, I seem to end up with the three signing addresses concatenated rather than the nice 3-prefix address I am seeking. Screenshots attached.

![https___counterwallet_io__pages_balances_html_1](https://cloud.githubusercontent.com/assets/10548240/5994819/a9ab5d36-aad6-11e4-9966-0c28a8054490.png)

![https___counterwallet_io__pages_balances_html](https://cloud.githubusercontent.com/assets/10548240/5994829/e8f81b28-aad6-11e4-8622-a2b939d44208.png)

**Comment by ouziel-slama** [comment]
In Counterparty we are not using P2SH but bare multisig addresses.
