### ISSUE TITLE
Allow `OP_RETURN`;  use`'auto'` encoding

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterwallet#688]
See https://github.com/CounterpartyXCP/counterpartyd/pull/691#issuecomment-72703360.

**Comment by ouziel-slama** [comment]
done here: https://github.com/CounterpartyXCP/counterwallet/commit/9924487433c0b1d5ae1397bc65d2866704573ae3

**Comment by btcdrak** [comment]
As far as I am aware this isnt enough

**Comment by btcdrak** [comment]
OK I've ported the remaining parts required to make counterwallet use OP_RETURNs where possible. After https://github.com/CounterpartyXCP/counterwebdeps/issues/6 is merged grunt will need to be updated for this repo.

**Comment by ouziel-slama** [comment]
@btcdrak: thanks again, I have updated the counterwebdeps version.
