### ISSUE TITLE
Can't log in to wallet

### ISSUE THREAD

**Issue by yampi1** [CounterpartyXCP/counterwallet#699]
failoverAPI: Call failed (failed over across all servers). Method: get_normalized_balances; Last     error: JSON-RPC Error:
    
    Type: Invalid params
    
    Code: -32602
    
    Message: UNSPECIFIED

This shows whenever I try to log in to my wallet.
This started to happen after I issued an asset with my BTC balance.

I tried to recreate this in testnet but in testnet there is no error.

**Comment by ouziel-slama** [comment]
Can you please look at the network tab of the javascript console, and send us the query which return this error at dev@counterparty.io ? the query should contains the addresses of your wallet.

**Comment by ouziel-slama** [comment]
Can you please retry now on https://cw01.counterwallet.io ?

**Comment by yampi1** [comment]
It works now.

**Comment by ouziel-slama** [comment]
fixed
