### ISSUE TITLE
Locked out of Counterwallet after creating an alphanumeric asset

### ISSUE THREAD

**Issue by ivanaszuber** [CounterpartyXCP/counterwallet#705]
After creating an alphanumeric asset and logging out of Counterwallet, the wallet is 'blocked' and there is no way to log in again. There is no error (nothing in the console), just stuck on loading.

When looking at the address in blockscan it shows the new asset.

![image](https://cloud.githubusercontent.com/assets/7252063/6370804/7fa128a6-bcf4-11e4-9ba0-e3f2510c714b.png)

When adding the address as a watch address in the other wallet, it doesn't show the newly created asset

![image](https://cloud.githubusercontent.com/assets/7252063/6370807/89fc95b0-bcf4-11e4-82b8-f9df1fe07aea.png)

**Comment by ouziel-slama** [comment]
Should be fixed with this: https://github.com/CounterpartyXCP/counterwallet/commit/d06bed3fc987b0bf875b6b38ee11a98beffe5879

**Comment by ivanaszuber** [comment]
I was not able to reproduce the issue after the upgrade, so yeah, should be fixed.
