### ISSUE TITLE
Cannot enter passphrase on Android

### ISSUE THREAD

**Issue by goodtaster** [CounterpartyXCP/counterwallet#724]
Users are saying impossible to enter the passphrase on the tablet for some reason (and they have to use the on-screen javascript keyboard). Clicking the passphrase field doesn't do anything.

Also, mobile support is currently quite (visually) unstable.
##

**Comment by rippler** [comment]
Maybe they're using a wrong browser. They should use one of supported ones.

A temporary workaround is to create a Quick Access URL and use that.

**Comment by goodtaster** [comment]
Yeah, I told them to use quick URL. If they are using an unsupported browser, doesn't the client deny access altogether?

**Comment by rippler** [comment]
Well the built in browser (for example) is not supported, but maybe it ID's itself as Chrome, and some other browser probably do the same, so if they lie, CW probably wouldn't show any particular warning about support.

**Comment by matthewjamesr** [comment]
@robby-dermody reccommend closing of this issue.
