### ISSUE TITLE
Submitting a Support ticket from CW gives an error

### ISSUE THREAD

**Issue by ivanaszuber** [CounterpartyXCP/counterwallet#729]
When trying to submit a support ticket from Counterwallet, this pops out:

```
failoverAPI: Call failed (failed over across all servers). Method: create_support_case; Last error: JSON-RPC Error:
Type: Server error

Code: -32000

Message: Sending of support emails are disabled on the server: no SUPPORT_EMAIL address set
```

**Comment by robby-dermody** [comment]
give it another try. 
this was due to https://github.com/CounterpartyXCP/federatednode_build/issues/238

**Comment by ivanaszuber** [comment]
I get a shorter message now

```
failoverAPI: Call failed (failed over across all servers). Method: create_support_case; Last error: undefined
```

I'll give another try later.

**Comment by ivanaszuber** [comment]
Ah sorry, seems CW is down again. I was already logged in when I tried this. I'll try when it's back up.

**Comment by robby-dermody** [comment]
Eh, counterblock is showing this again: ```2015-04-22-T17:06:41+0000:WARNING:util:Bad status code returned: '503'. result body: '{"data": "Counterparty database is behind backend.", "code": -32000, "message": "Server error"}'. -- Waiting 3 seconds before trying again...```

connection problem to counterparty-server. I'll restart bitcoind/counterparty-server and see if that resolves it.

**Comment by ivanaszuber** [comment]
CW is back online but I still get the error :/
