### ISSUE TITLE
Connection refused error code -32000 on login

### ISSUE THREAD

**Issue by benjaminmbrown** [CounterpartyXCP/counterwallet#731]
After clicking "Open Wallet", popup modal says:

failoverAPI: Call failed (failed over across all servers). Method: get_normalized_balances; Last error: JSON-RPC Error:
Type: Server error

Code: -32000

Message: Got call_jsonrpc_api request error: [Errno 111] Connection refused

**Comment by robby-dermody** [comment]
transient error, will be making this more reliable
