### ISSUE TITLE
Unicode Description in asset name not recognized (Undefined) by CW

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterwallet#740]
Issued `XCHINESETEST ` from `mndnMzJuAqgHcGpCqBMH4Ehurb1FmnSzhA`, put some Chinese characters in Description.

`8/10/15 8:59:20pm	Token created with description 'Undefined' and total issuance of 100 units. Owned by address My Address #1`

**Comment by unsystemizer** [comment]
Clarification: this appears to be a CW-only problem (counterblock is not affected).

**Comment by robby-dermody** [comment]
I created an asset with Chinese characters... displays fine in the asset info dialog and updating the desc with more chinese chars works too
