### ISSUE TITLE
Bubble up reorg warnings and status/counter to CW 

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterwallet#743]
It seems reorgs won't get any less frequent soon.
`counterparty-lib` already reports blockchain reorgs.
If we could bubble those to somewhere in the GUI, users would be able to see and estimate when they can be back. Maybe existing messages around https://github.com/CounterpartyXCP/counterwallet/blob/09998cef96c6bc99a35d73d4b23db922172d6ac6/src/js/components/logon.js#L131 could be improved.

Example:
`Warning: blockchain reorganization at block X started Y minutes ago, please be patient until the blockchain is reparsed`

**Comment by robby-dermody** [comment]
this shouldn't be an issue anymore due to the fixes undolog with counterparty-lib (i.e. reorgs are handled very quickly)
