### ISSUE TITLE
Counterwallet invailidates Multisig bitcoin address

### ISSUE THREAD

**Issue by tjoppert** [CounterpartyXCP/counterwallet#745]
This morning I was trying to get some BTC out of Counterwallet to a new multisignature wallet.
However I found out that Counterwallet inavalidates Mulsignature addresses starting with a 3, so I was not able to send it out.

Is there a way to still send this transaction or can we add the verify address for multisignature ? 
##

**Comment by deweller** [comment]
Counterparty doesn't support multisig (P2SH) addresses yet.  That is why Counterwallet won't let you send to a 3xxxx address.

See https://github.com/CounterpartyXCP/counterparty-lib/issues/791.

**Comment by robby-dermody** [comment]
once p2sh is pushed, we will enhance validation logic to support '3' addresses
