### ISSUE TITLE
Address action is broken

### ISSUE THREAD

**Issue by sammy007** [CounterpartyXCP/counterwallet#765]
![screen shot 2015-12-06 at 17 08 00](https://cloud.githubusercontent.com/assets/7374093/11613243/fa7cb636-9c3b-11e5-8a9f-b76c3990b2ea.png)
##

**Comment by unsystemizer** [comment]
Maybe you're using a browser that's not supported?

![image](https://cloud.githubusercontent.com/assets/13134193/11613494/a694782a-9c5d-11e5-8413-f8139ff222a2.png)

Do you have a recent Firefox or Chrome?

**Comment by sammy007** [comment]
Sure I have recent firefox or chrome.

**Comment by sammy007** [comment]
I have 2 addresses, on one that is below, this happens. The first one is ok (not transparent like 2nd) but both are unusable because all submenus are unreadable/unreachable. I think they should be expanded to the opposite side.

**Comment by robby-dermody** [comment]
is this still an issue, and can be it reproduced? may be fixed by #776 if still a problem
