### ISSUE TITLE
Blockexplorer link fails DNS lookup

### ISSUE THREAD

**Issue by x-ETHeREAL-x** [CounterpartyXCP/counterwallet#773]
Hey guys in **counterwallet/src/js/consts.js**

you have this at line 239:

`var BLOCKEXPLORER_URL = USE_TESTNET ? "http://test.bitcore.io" : "http://live.bitcore.io";`

Those subdomains fail. I would suggest:

`var BLOCKEXPLORER_URL = USE_TESTNET ? "http://testnet.blockscan.com/" : "https://blockscan.com/";`

Then: **counterwallet/src/js/util.js**
Line 224 should be: 

` var url = BLOCKEXPLORER_URL + 'tx?block=' + blockIndex;`

**Comment by unsystemizer** [comment]
Do you mind to submit a pull request against source in `develop` branch?

**Comment by x-ETHeREAL-x** [comment]
Sure, i can do it this weekend.

**Comment by robby-dermody** [comment]
Change to use counterpartychain, as blockscan has no testnet explorer
