### ISSUE TITLE
Asset locking function generates JS error

### ISSUE THREAD

**Issue by daxxog** [CounterpartyXCP/counterwallet#775]
I own the token DARKCLAM and would like to lock the issuance. How would I go about doing that?

I hit "Lock Token Issuance" and it throws this error in the console on Chrome: (Also not working on Safari and Firefox)
```
Uncaught TypeError: onError is not a function(anonymous function)
@ counterwallet-min.js?v=bdaab26f0f42:35(anonymous function)
@ counterwallet-min.js?v=bdaab26f0f42:35(anonymous function)
@ counterwallet-min.js?v=bdaab26f0f42:13setTimeout (async)_delay
@ counterwallet-deps-min.js?v=e832848b6cf8:461CWPrivateKey.checkAndSignRawTransaction
@ counterwallet-min.js?v=bdaab26f0f42:13WalletViewModel.self.signAndBroadcastTxRaw
@ counterwallet-min.js?v=bdaab26f0f42:35WalletViewModel.self.signAndBroadcastTx
@ counterwallet-min.js?v=bdaab26f0f42:35(anonymous function)
@ counterwallet-min.js?v=bdaab26f0f42:35(anonymous function)
@ counterwallet-min.js?v=bdaab26f0f42:15gatheredResults.push.success
@ counterwallet-min.js?v=bdaab26f0f42:15ajaxOpts.success
@ counterwallet-min.js?v=bdaab26f0f42:15l
@ counterwallet-deps-min.js?v=e832848b6cf8:10c.fireWith
@ counterwallet-deps-min.js?v=e832848b6cf8:10k
@ counterwallet-deps-min.js?v=e832848b6cf8:12(anonymous function)
@ counterwallet-deps-min.js?v=e832848b6cf8:12XMLHttpRequest.send (async)x.support.cors.e.crossDomain.send
@ counterwallet-deps-min.js?v=e832848b6cf8:12x.extend.ajax
@ counterwallet-deps-min.js?v=e832848b6cf8:12fetchData
@ counterwallet-min.js?v=bdaab26f0f42:15makeJSONRPCCall
@ counterwallet-min.js?v=bdaab26f0f42:15_makeJSONAPICall
@ counterwallet-min.js?v=bdaab26f0f42:15_multiAPIPrimative
@ counterwallet-min.js?v=bdaab26f0f42:15multiAPIConsensus
@ counterwallet-min.js?v=bdaab26f0f42:15WalletViewModel.self.doTransaction
@ counterwallet-min.js?v=bdaab26f0f42:35bootbox.dialog.buttons.danger.callback
@ counterwallet-min.js?v=bdaab26f0f42:41processCallback
@ counterwallet-deps-min.js?v=e832848b6cf8:297(anonymous function)
@ counterwallet-deps-min.js?v=e832848b6cf8:297x.event.dispatch
@ counterwallet-deps-min.js?v=e832848b6cf8:11y.handle
@ counterwallet-deps-min.js?v=e832848b6cf8:11
```

Difficult for me to figure out what the error means due to minification, but maybe one of the developers here could help me? I'm on the official counterwallet server.

**Comment by unsystemizer** [comment]
Can you try in "private" mode, without any extensions? 
I just tried on testnet.counterwallet.io and it worked fine for me in Opera

**Comment by daxxog** [comment]
Still got the same "TypeError: onError is not a function" on Chrome (latest) in incognito mode. I'll test on Opera private tommorow.

**Comment by daxxog** [comment]
Tested on Opera (latest version on Mac) in private mode. Still getting the same "Uncaught TypeError: onError" error.

**Comment by unsystemizer** [comment]
Have you tried on Coindaddy's CW, by any chance?

**Comment by daxxog** [comment]
Coindaddy is currently down, but I did test on it earlier and got the same results.
![screen shot 2016-03-23 at 9 34 53 am](https://cloud.githubusercontent.com/assets/2145492/13986761/8b0d4542-f0da-11e5-8add-afe59cea0c57.png)

**Comment by unsystemizer** [comment]
I tried on the official CW before on testnet and few hours ago on mainnet (using a free asset), it works for me.

https://www.dropbox.com/s/9gsbeo71bib3j59/lock-tocken-issuance.mp4?dl=0

**Comment by daxxog** [comment]
Still not working for me. Tried four different browsers. Tried "private" mode on all browsers. Tried coindady mirror. Nothing is working for me.
![screen shot 2016-03-25 at 10 19 31 pm](https://cloud.githubusercontent.com/assets/2145492/14057495/bc03ccf8-f2d7-11e5-84cf-4c8ec37ebbef.png)

**Comment by unsystemizer** [comment]
@robby-dermody could it be something specific to the wallet cache?

**Comment by daxxog** [comment]
Is there any possible way for me to "manually" sign/broadcast a bitcoin transaction that can lock my token for me?

**Comment by robby-dermody** [comment]
This is probably a bug with counterwallet. If you have `counterparty-client` you can lock it. You'd send an issuance command with the description set to LOCK (https://github.com/CounterpartyXCP/counterparty-cli/blob/master/counterpartycli/client.py#L103). If you have that, we can help further there. I will try to fix this bug when I have the time

**Comment by robby-dermody** [comment]
this may be fixed with the update we just made (https://github.com/CounterpartyXCP/counterwallet/commit/4ff9b2f288244aeb18edbf8278df04dd4e50ada) ....i.e. could have been an underlying bitcore tx validation issue, looking at that traceback

this update will be live on new CW servers in a few days

**Comment by robby-dermody** [comment]
update going live today. I tested locking an asset on testnet and it worked. please reopen this if still an issue
