### ISSUE TITLE
update smartadmin and other deps to newest versions

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterwallet#776]
There's a handful of warnings when building CW, I captured some of them

```
2016-03-27 12:59:35,581|DEBUG: RUNNING COMMAND: cd ~xcp/counterwallet && npm install
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@1.1.14: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN engine escodegen@1.7.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN deprecated npmconf@0.0.24: this package has been reintegrated into npm and is now out of date with respect to npm

```
##

**Comment by robby-dermody** [comment]
this seems to be deps of other deps we use. revising the issue

**Comment by robby-dermody** [comment]
ATM newest smartadmin version appears to be 1.8.2 (https://wrapbootstrap.com/theme/smartadmin-responsive-webapp-WB0573SK0)

**Comment by John1128** [comment]
Hi Robby. 
How are you? I hope you are okay and safe from COVID.
I'm using SmartAdmin v1.4 built in 2017 years. For now, I'm going to upgrade current version to SmartAdmin v4.4.5. So I purchased the new SmartAdmin package from wrapbootstrap marketplace, and I checked new version at all. But I think, the v1.4 is built using general PHP, HTML/CSS and the new version is built handlebars.js ( webpack ), so it's not the same completely between 2 versions.
So I'm a bit confused how to migrate v1.4 to v4.4.5. And how to use PHP code and variables in handlebars.js, if you have any idea for migrating, please let me know. I really need to know it clearly.
Thanks.

**Comment by robby-dermody** [comment]
Hi @John1128, I just checked and it looks like they still have the PHP Smartadmin maintained as a separate project: https://wrapbootstrap.com/theme/smartadmin-php-7-responsive-webapp-WB05M9585

Hope that helps

**Comment by John1128** [comment]
Thank you for your reply and information. I will check this URL.
Thank you again.

**Comment by John1128** [comment]
Yes, you are right. Thanks again.
