### ISSUE TITLE
Support URLs need to be updated

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterwallet#777]
Here:
https://github.com/CounterpartyXCP/counterwallet/blob/master/src/index.html#L608

**Comment by robby-dermody** [comment]
Can you submit a PR with the right URLs?

**Comment by robby-dermody** [comment]
@unsystemizer

**Comment by unsystemizer** [comment]
Will try to find time this coming weekend

**Comment by robby-dermody** [comment]
updated in #782
