### ISSUE TITLE
Misleading Broadcast Date picker in Broadcast form

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterwallet#779]
Regardless of what one selects, date/time is always "as expected":

`2016-04-30-T11:15:37+0000 [INFO] Broadcast: .... at 2016-04-30T11:12:19+00:00 ... [valid]`

But in the UI it appears as if the date/time selected actually has some effect, which doesn't seem to be the case.

![image](https://cloud.githubusercontent.com/assets/13134193/14935601/35449388-0f0a-11e6-9f55-017fc7de9562.png)

**Comment by robby-dermody** [comment]
so you mean that the broadcast date field doesn't do anything, essentially, and should be removed?

**Comment by unsystemizer** [comment]
Right. I made broadcasts with random non-current dates and times and couldn't tell any difference. 
If selecting a non-current date actually does something it should be left (and we could document what that achieves).
