### ISSUE TITLE
UI tweaks part 1

### ISSUE THREAD

**Issue by robby-dermody** [CounterpartyXCP/counterwallet#780]
Some overdue minor UI tweaks:
* remove "my portfolio" and "top assets": These aren't used and don't work well anymore. Instead of fixing them, remove them from the UI for now. we may want to add them back later, or not.
* Remove the "more" button, and put Network Stats on the top bar instead of the left bar
* remove the "minus" icon on the top bar (which collapses/shows the side bar)??? or is there ever a case where this is useful (e.g. we already have an arrow button on the side bar itself)

anything else? @unsystemizer @rubensayshi @x-ETHeREAL-x

**Comment by unsystemizer** [comment]
* Make it possible to easily copy wallet address to clipboard by clicking on it (either twice, or select+copy to clipboard). Currently when one clicks on wallet address that opens a modal on which one has to click the address again to copy it to clipboard

I'll have to poke around and check the forum and personal notes to see if there's more in which case I'd add it here.
