### ISSUE TITLE
Login not possible with firefox 48.0.2

### ISSUE THREAD

**Issue by littleskunk** [CounterpartyXCP/counterwallet#791]
Login is not possible with firefox 48.0.2. All I see is this:

![counterwallet](https://cloud.githubusercontent.com/assets/6333390/18029763/8ade2210-6ca1-11e6-9fe1-8c7ca464afa9.jpg)

Webconsole output for a new created wallet:

```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# insteadcounterwallet-deps-min.js:7
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented.counterwallet-deps-min.js:11:12584
[27/8/2016 22:1:12.96] Backend is ready. Testnet status: false. Last message feed index: 1858790. CW last message seq: 167819counterwallet-deps-min.js:457:1819
[27/8/2016 22:1:12.102] My wallet ID: JOy4n9Zk+rbluRBPytatRMA8PU9nXNb710tnfjRyXgM=counterwallet-deps-min.js:457:1819
[27/8/2016 22:1:12.363] Stored preferences NOT found on server(s). Creating new...counterwallet-deps-min.js:457:1819
AssertionError: chainCode has not the expected size: found 64, expected 32(unbekannt)
```

Same problem you can read here:
https://forums.counterparty.io/t/problem-login-into-counterwallet/2281
https://forums.counterparty.io/t/cant-log-in-counterwallet/2239

One community member was using v47.0.1 and everything was running fine. After firefox update he has now the same problem. It is not working anymore.
##

**Comment by unsystemizer** [comment]
Maybe because FF removed support for "@", see 
https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Errors/Deprecated_source_map_pragma
If they have some "Compatibility Mode" setting maybe they can use that for CW until this is fixed.

**Comment by unsystemizer** [comment]
1) This is related to #292 
![image](https://cloud.githubusercontent.com/assets/13134193/19425313/85c3941a-9463-11e6-8c28-3098cc303b13.png)
2) Firefox doesn't have a "Compatibility Mode", so for now older Firefox or another browser have to be used

**Comment by unsystemizer** [comment]
OT comment: the forum URL changed to https://counterpartytalk.org/ last year; the old forums link still works, but the SSL cert isn't valid for that domain.

**Comment by robby-dermody** [comment]
fixed in newest code (updated bitcore)
