### ISSUE TITLE
Duplicate "word 8" in passphrase input window

### ISSUE THREAD

**Issue by heunland** [CounterpartyXCP/counterwallet#805]
As shown in the screenshot below, a user that clicks on the keyboard icon on the main wallet login screen to get the option to enter their passphrase for counterwallet one word at a time, is presented with a screen with 12 text boxes for the 12 words of the phrase, however, there are two boxes labeled "Word 8". The second one of those boxes should be labeled "Word 9". 

![image](https://cloud.githubusercontent.com/assets/8723695/20892601/7d7cc640-bad4-11e6-8bd8-e6ee2ec63615.png)

**Comment by matthewjamesr** [comment]
@robby-dermody Please close this, #806 closes.
