### ISSUE TITLE
Evaluate asset description length, use pubkeyhash for 42-52 byte long description

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterwallet#810]
Counterwallet can't effect asset description change for over 41 bytes.

Somewhere around here (or before), description string length could be evaluated and if > 41 and < 53 bytes, we could set encoding to pubkeyhash.

https://github.com/CounterpartyXCP/counterwallet/blob/542d63f887c70c426b3b62a8deed757db0d63b43/src/js/components/balances.js#L1145

**Comment by deweller** [comment]
I say let's wait until CIP-6 is enabled and then we can use P2SH data encoding for longer descriptions

**Comment by deweller** [comment]
Fixed by https://github.com/CounterpartyXCP/counterparty-lib/pull/1005
