### ISSUE TITLE
Blockscan is out of peration, need to update links in the wallet.

### ISSUE THREAD

**Issue by Dorson** [CounterpartyXCP/counterwallet#813]
The wallet is linking addresses to the blockscan explorer, which went out of operation.

The links need to point to a different block / address explorer now.

https://counterpartychain.io works well as the block explorer for counterparty.

It's a quick fix with fast results.

**Comment by jdogresorg** [comment]
already updated in https://github.com/CounterpartyXCP/counterwallet/pull/817
