### ISSUE TITLE
Where can i buy  Counterparty? BTC-E ? Bitfinex? BitYep?

### ISSUE THREAD

**Issue by algorithmcode** [CounterpartyXCP/counterwallet#822]
Thanks!

**Comment by jdogresorg** [comment]
You should be asking your question on a support forum like Counterpartytalk.org as it is a general question.

Github is for reporting specific issues with details, not for getting answers to general questions.

**Comment by deweller** [comment]
Agreed.  Github is for questions about code.  But you can find your answer here:

https://counterparty.io/get-started/
